name: Build DokuWiki Plugin ZIP and Changelog on version tag (i.e., v1.0.0)

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest

    env:
      INCLUDE_FILES: |
        inc/
        conf/
        LICENSE
        plugin.info.txt
        syntax.php
        README.md

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract plugin name from repo name
        id: extract_plugin_name
        run: |
          repo="${GITHUB_REPOSITORY##*/}"
          prefix="dokuwiki-plugin-"
          if [[ "$repo" == "$prefix"* ]]; then
            plugin_name="${repo#$prefix}"
          else
            plugin_name="$repo"
          fi
          echo "PLUGIN_NAME=$plugin_name" >> "$GITHUB_ENV"
          echo "TAG_NAME=${GITHUB_REF_NAME}" >> "$GITHUB_ENV"
          echo "VERSION=${GITHUB_REF_NAME#v}" >> "$GITHUB_ENV"

      - name: Install git-cliff
        run: |
          curl -sSL https://github.com/orhun/git-cliff/releases/download/v2.10.0/git-cliff-2.10.0-x86_64-unknown-linux-gnu.tar.gz | tar -xz
          sudo mv git-cliff-2.10.0/git-cliff /usr/local/bin/git-cliff
          git-cliff --version

      - name: Generate CHANGELOG.md
        run: |
          if [[ -f cliff.toml ]]; then
            echo "Generating changelog for ${TAG_NAME}"
            git-cliff --config cliff.toml --tag "${TAG_NAME}" -o CHANGELOG.md
          else
            echo "Generating changelog for ${TAG_NAME} with fallback config"
            cat >/tmp/_cliff.toml <<-'EOF'
          [changelog]
          header = "# Changelog"
          trim = true
          [git]
          conventional_commits = true
          filter_commits = true
          tag_pattern = "v[0-9].*"
          topo_order = false
          EOF
            git-cliff --config /tmp/_cliff.toml --tag "${TAG_NAME}" -o CHANGELOG.md
          fi

      - name: Verify plugin.info.txt exists
        run: |
          if [[ ! -f plugin.info.txt ]]; then
            echo "::error title=Missing plugin.info.txt::plugin.info.txt is required at repo root."
            exit 1
          fi

      - name: Build release ZIP
        run: |
          set -euo pipefail
          STAGE="build/stage"
          OUTDIR="build"
          mkdir -p "$STAGE" "$OUTDIR"
          
          DEST="$STAGE/${PLUGIN_NAME}"
          rm -rf "$DEST"
          mkdir -p "$DEST"
          
          while IFS= read -r item; do
            # skip blank lines
            [[ -z "${item// }" ]] && continue
          
            # normalize: remove trailing slash so rsync copies the directory itself
            src="${item%/}"
          
            if [[ -e "$src" ]]; then
              echo "Adding $src"
              rsync -a "$src" "$DEST"/
            else
              echo "Skipping missing $item"
            fi
          done <<< "${INCLUDE_FILES}"
          
          echo "Staged tree:"
          find "$DEST" -maxdepth 2 -print | sed "s|$DEST|.|"
          
          # Normalize plugin.info.txt date
          if [[ -f "$DEST/plugin.info.txt" ]]; then
            today=$(TZ=America/Chicago date +'%Y-%m-%d')
            tmp="$DEST/plugin.info.txt.tmp"
            { sed '1s/^\xEF\xBB\xBF//' "$DEST/plugin.info.txt" || cat "$DEST/plugin.info.txt"; } > "$tmp"
            awk -v today="$today" '
              BEGIN { OFS="\t" }
              /^[[:space:]]*date([[:space:]]|$)/ { print "date", today; next }
              { print $0 }
            ' "$tmp" > "$DEST/plugin.info.txt"
            rm -f "$tmp"
          fi
          
          ZIP_FILE="${OUTDIR}/${PLUGIN_NAME}-${TAG_NAME}.zip"
          rm -f "$ZIP_FILE"
          (cd "$STAGE" && zip -r -q "../${PLUGIN_NAME}-${TAG_NAME}.zip" "${PLUGIN_NAME}")
          
          cp CHANGELOG.md "$OUTDIR"/
          (cd "$OUTDIR" && sha256sum "${PLUGIN_NAME}-${TAG_NAME}.zip" > "${PLUGIN_NAME}-${TAG_NAME}.zip.sha256")
          
          echo "ZIP_FILE=$ZIP_FILE" >> "$GITHUB_ENV"

      - name: Verify ZIP directory structure
        run: |
          set -euo pipefail
          echo "Verifying contents of $ZIP_FILE..."
          unzip -l "$ZIP_FILE"

          echo "Checking required directories and files..."
          unzip -l "$ZIP_FILE" | grep -q "${PLUGIN_NAME}/inc/"      || { echo "::error::Missing inc/ directory"; exit 1; }
          unzip -l "$ZIP_FILE" | grep -q "${PLUGIN_NAME}/conf/"     || { echo "::error::Missing conf/ directory"; exit 1; }
          unzip -l "$ZIP_FILE" | grep -q "${PLUGIN_NAME}/plugin.info.txt" || { echo "::error::Missing plugin.info.txt"; exit 1; }
          unzip -l "$ZIP_FILE" | grep -q "${PLUGIN_NAME}/syntax.php"      || { echo "::error::Missing syntax.php"; exit 1; }
          unzip -l "$ZIP_FILE" | grep -q "${PLUGIN_NAME}/README.md"       || { echo "::error::Missing README.md"; exit 1; }
          unzip -l "$ZIP_FILE" | grep -q "${PLUGIN_NAME}/LICENSE"         || { echo "::error::Missing LICENSE"; exit 1; }

          echo "ZIP structure verified successfully!"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          body_path: build/CHANGELOG.md
          files: |
            ${{ env.ZIP_FILE }}
            ${{ env.ZIP_FILE }}.sha256
            build/CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          