name: Build DokuWiki Plugin ZIP and Changelog on version tag (i.e., v1.0.0)

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest

    env:
      INCLUDE_FILES: |
        plugin.info.txt
        README.md
        LICENSE
        action.php
        admin.php
        helper.php
        helper_*.php
        metadata.php
        metadata_*.php
        install.php
        meta.php
        syntax.php
        conf/
        lang/
        doc/
        tpl/
        styles.css
        script.js
        config/
        tests/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract plugin name from repo name
        id: extract_plugin_name
        run: |
          repo="${GITHUB_REPOSITORY##*/}"
          prefix="dokuwiki-plugin-"
          if [[ "$repo" == "$prefix"* ]]; then
            plugin_name="${repo#$prefix}"
          else
            plugin_name="$repo"
          fi
          echo "PLUGIN_NAME=$plugin_name" >> "$GITHUB_ENV"

      - name: Setup git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Install git-cliff
        run: |
          curl -sSL https://github.com/orhun/git-cliff/releases/download/v2.10.0/git-cliff-2.10.0-x86_64-unknown-linux-gnu.tar.gz | tar -xz
          sudo mv git-cliff-2.10.0/git-cliff /usr/local/bin/git-cliff
          git-cliff --version

      - name: Generate CHANGELOG.md from commits
        run: git-cliff --config cliff.toml -o CHANGELOG.md

      - name: Update plugin date in plugin.info.txt
        run: |
          today=$(TZ=America/Chicago date +'%Y-%m-%d')

          if grep -q "^date" plugin.info.txt; then
            sed -i "s/^date[[:space:]]\+[0-9-]\+/date   ${today}/" plugin.info.txt
          else
            echo "date   ${today}" >> plugin.info.txt
          fi

          echo "Updated plugin date to ${today}"
          cat plugin.info.txt

          # Commit only if there are changes
          if ! git diff --quiet plugin.info.txt; then
            git add plugin.info.txt
            git commit -m "chore: update plugin.info.txt date to ${today}"
            git push
          else
            echo "No changes to commit"
          fi

      - name: Create plugin zip
        run: |
          set -euo pipefail
          shopt -s nullglob
          mkdir -p build
          zip_file="build/${PLUGIN_NAME}.zip"
          rm -f "$zip_file"
          echo "Creating ZIP: $zip_file"

          # iterate each line from INCLUDE_FILES, expand globs, add if present
          while IFS= read -r item; do
            [[ -z "$item" ]] && continue
            found=0
            for path in $item; do
              if [[ -e "$path" ]]; then
                found=1
                echo "Adding $path"
                zip -r -q "$zip_file" "$path"
              fi
            done
            if [[ $found -eq 0 ]]; then
              echo "Skipping missing $item"
            fi
          done <<< "${INCLUDE_FILES}"

          cp CHANGELOG.md build/

      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body_path: build/CHANGELOG.md
          files: |
            build/${{ env.PLUGIN_NAME }}.zip
            build/CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
