name: Build DokuWiki Plugin ZIP and Changelog on version tag (i.e., v1.0.0)

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    runs-on: ubuntu-latest
    env:
      INCLUDE_FILES: |
        plugin.info.txt
        README.md
        LICENSE
        action.php
        admin.php
        helper.php
        helper_*.php
        metadata.php
        metadata_*.php
        install.php
        meta.php
        syntax.php
        conf/
        lang/
        doc/
        tpl/
        styles.css
        script.js
        config/
        tests/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract plugin name from repo name
        id: extract_plugin_name
        run: |
          # get repo name only
          repo="${GITHUB_REPOSITORY##*/}"
          prefix="dokuwiki-plugin-"
          if [[ "$repo" == "$prefix"* ]]; then
            plugin_name="${repo#$prefix}"
          else
            plugin_name="$repo"
          fi
          echo "PLUGIN_NAME=$plugin_name" >> $GITHUB_ENV

      - name: Setup git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Install git-cliff
        run: |
          curl -sSL https://github.com/orhun/git-cliff/releases/download/v2.10.0/git-cliff-2.10.0-x86_64-unknown-linux-gnu.tar.gz | tar -xz
          sudo mv git-cliff-2.10.0/git-cliff /usr/local/bin/

      - name: Generate CHANGELOG.md from commits
        run: git-cliff -o CHANGELOG.md

      - name: Create plugin zip
        run: |
          mkdir -p build
          # Loop through files and add existing ones to ZIP to avoid failure
          zip_file="build/${PLUGIN_NAME}.zip"
          rm -f "$zip_file"
          echo "Creating ZIP: $zip_file"
          while IFS= read -r item; do
            if [ -e "$item" ]; then
              echo "Adding $item"
              zip -r -q "$zip_file" "$item"
            else
              echo "Skipping missing $item"
            fi
          done <<< "${INCLUDE_FILES}"
          cp CHANGELOG.md build/

      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body_path: build/CHANGELOG.md
          files: |
            build/${{ env.PLUGIN_NAME }}.zip
            build/CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
