name: ifday plugin tests

on:
  pull_request:
    paths:
      - "syntax.php"
      - "tests/**"
      - ".github/workflows/ifday-tests.yml"
  workflow_dispatch:

jobs:
  test:
    name: PHP ${{ matrix.php }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: ["8.2", "8.3", "8.4"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          ini-values: display_errors=On, error_reporting=-1

      - name: Show PHP version
        run: php -v

      # Run standalone runner in quiet mode (prints only FAIL lines + summary).
      - name: Run ifday tests (quiet)
        env:
          QUIET: "1"    # only FAIL lines + summary
        run: |
          set -e
          php tests/run_ifday_tests.php | tee test-output-${{ matrix.php }}.log

      # If the job fails, upload the full output so it’s easy to debug from the PR.
      - name: Upload test logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ifday-test-output-php-${{ matrix.php }}
          path: test-output-${{ matrix.php }}.log
