name: Validate Conventional Commits

on:
  workflow_call: {}   # reusable; runs only when called from PR Check

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            chore
            docs
            style
            refactor
            perf
            test
            build
            ci
            improvement
            build
            wip
            revert
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
